name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # carousel_pro: ^1.0.0
  # flutter_carousel_slider: ^1.0.1
  # google_fonts: ^0.5.0+1
  google_sign_in: ^4.1.1
  flutter_rating_bar: ^3.2.0
  flutter_facebook_login: ^3.0.0
  timeago: ^2.0.17
  geolocator: ^5.3.2
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.4
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^0.5.0+1
  image: ^2.0.7
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/login1.png
    - images/admin.png
    - images/cash.png
    - images/google.png
    - images/icon_facebook.png
    - images/Logo.png
    - holding-phone.png
    - images/findProduct.jpg
    - images/pexels-markus-spiske-2818573.jpg
    - images/pexels-zen-chung-5529014.jpg
    - images/girl.png
    - images/pexels-zen-chung-5529001.jpg
    



